GET http://localhost:8080/api/v1/country

###

POST http://localhost:8080/api/v1/config/delay
Content-Type: application/json

0

###

POST http://localhost:8080/api/v1/config/activate
Content-Type: application/json

false

###

GET http://localhost:8080/actuator/metrics/http.server.requests